<?php
$form->prepare();
$escapeHtml = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Map Omeka properties'), 1, $this->translate('Omeka-S Classic Importer')); ?>

<?php echo $this->form()->openTag($form); ?>
<?= $this->formRow($form->get('csrf')); ?>
<?= $this->formRow($form->get('files_source')); ?>
<?= $this->formRow($form->get('domain_name')); ?>
<?= $this->formRow($form->get('import_collections')); ?>
<?= $this->formRow($form->get('update')); ?>

<fieldset id='page-actions'>
    <button type="submit"><?php echo $this->translate('Next'); ?></button>
</fieldset>

<?php if (!empty($properties)): ?>
<table class="tablesaw tablesaw-stack">
    <thead>
        <tr>
            <th><?= $this->translate('Omeka vocabulary name'); ?></th>
            <th><?= $this->translate('Omeka property'); ?></th>
            <th><?= $this->translate('Omeka-S property'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($properties as $index => $property): ?>
            <tr>
                <td><?= $this->escapeHtml($property['element_set_name']); ?></td>
                <td><?= $this->escapeHtml($property['element_name']); ?></td>
                <td>
                    <?= $this->formElement($form->get('elements_properties[' . $property['element_id'] . ']')); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<?php if (!empty($resourceClasses)): ?>
<table class="tablesaw tablesaw-stack">
    <thead>
        <tr>
            <th><?= $this->translate('Omeka class name'); ?></th>
            <th><?= $this->translate('Omeka class description'); ?></th>
            <th><?= $this->translate('Omeka-S class'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceClasses as $index => $resourceClass): ?>
        </tr>
            <td><?= $this->escapeHtml($resourceClass['name']); ?></td>
            <td><?= $this->escapeHtml($resourceClass['description']); ?></td>
            <td> 
                <?= $this->formElement($form->get('types_classes[' . $resourceClass['id'] . ']')); ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<?php echo $this->form()->closeTag($form); ?>

